version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - internal


  notifications:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notifications
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    ports:
      - "50051:50051"
    networks:
      - internal

networks:
  internal:
    driver: bridge
